/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#d8e2ff",
        "outline-variant": "#424754",
        primary: "#adc6ff",
        "surface-variant": "#353534",
        "on-background": "#e5e2e1",
        "primary-fixed-dim": "#adc6ff",
        "tertiary-container": "#df7412",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary": "#502400",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#1a1c1c",
        "surface-container-low": "#1c1b1b",
        "on-tertiary-container": "#461f00",
        "on-secondary-container": "#b5b5b5",
        "on-primary-container": "#00285d",
        "on-secondary-fixed-variant": "#454747",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#311400",
        "tertiary-fixed": "#ffdcc6",
        "on-tertiary-fixed-variant": "#723600",
        "surface-tint": "#adc6ff",
        "surface-container": "#201f1f",
        "inverse-primary": "#005ac2",
        surface: "#131313",
        "surface-container-high": "#2a2a2a",
        "on-secondary": "#2f3131",
        secondary: "#c6c6c6",
        outline: "#8c909f",
        "on-surface": "#e5e2e1",
        tertiary: "#ffb786",
        "tertiary-fixed-dim": "#ffb786",
        "secondary-container": "#454747",
        "secondary-fixed": "#e2e2e2",
        "on-primary-fixed-variant": "#004395",
        "surface-dim": "#131313",
        "on-primary-fixed": "#001a42",
        "surface-container-highest": "#353534",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "on-surface-variant": "#c2c6d6",
        "secondary-fixed-dim": "#c6c6c6",
        "on-primary": "#002e6a",
        error: "#ffb4ab",
        "primary-container": "#4d8eff",
        background: "#131313",
        "surface-bright": "#393939",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        lg: "24px",
        xs: "4px",
        "margin-mobile": "16px",
        md: "16px",
        xl: "48px",
        sm: "8px",
        gutter: "16px",
        unit: "4px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-sm": [
          "13px",
          { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "body-lg": [
          "15px",
          { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "body-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "label-caps": [
          "11px",
          {
            lineHeight: "16px",
            letterSpacing: "0.05em",
            fontWeight: "700",
          },
        ],
        "headline-sm": [
          "20px",
          {
            lineHeight: "28px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "code-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" },
        ],
      },
    },
  },
  plugins: [],
}
